### ISSUE TITLE
[Question] face index in read.fs.surface

### ISSUE THREAD

**Issue by dipterix** [dfsp-spirit/freesurferformats#11]
Hi, @dfsp-spirit ,

I noticed a change(?) in `read.fs.surface`: it's face index now starts from `1`. Is that change going to be in the future versions?

That brings me to a question: do you have any plan like from version xxx, file formats will be backward compatible? It'll be very nice if the format is consistent so that labs using your package could build a code repo that won't break easily.

One suggestion is you can make your return type `environment`, or `R6Class` so that you can use active bindings

```r

# Just to store data, parent can be empty env
val <- new.env(parent = emptyenv())

# version 0.1, old formats
val$faces <- c(0,1,2)
val$faces

# > [1] 0 1 2

# version 0.2, new format, old one is available, but with "depricate" warning
# Now using a new format, the old format will result in a warning
val$faces2 <- 1:3
if(exists('faces', envir = val)){
  rm('faces', envir = val)
}
makeActiveBinding('faces', function(){
  warning('result$faces is depricated, use $faces2 instead')
  val$faces2 - 1
}, val)
val$faces

# > [1] 0 1 2
# > Warning message:
# >   In (function ()  : result$faces is depricated, use $faces2 instead
```

Best :)

**Comment by dipterix** [comment]
An `R6Class` example:
```r
FsSurface <- R6::R6Class(
  classname = 'fs.surface',
  private = list(
    .faces = NULL
  ),
  public = list(
    format = 'asc',
    
    #' @description Constructor
    #' @param vert vertice positions, matrix
    #' @param face face indices, integer matrix starting from 0
    initialize = function(vert, face){
      private$.faces = face + 1
    }
  ),
  active = list(
    
    #' @field faces face indices, starting from 0, depricated
    faces = function(){
      warning('result$faces is depricated, use $faces2 instead')
      private$.faces - 1
    },
    
    #' @field faces face indices, starting from 1
    faces2 = function(){
      private$.faces
    }
  )
)

# In read.fs.surface
results <- FsSurface$new(NULL, 0:2)
results$faces
```

**Comment by dfsp-spirit** [comment]
Hi dipterix,

The indices should start at 1, like it is in R. I think you are referring to surfaces in GIFTI format, right? It was a bug in earlier versions that they started at 0, and the current behaviour (starting at 1) will persist in future versions.

It differs for each mesh file format whether the indices in the files start at 0 or at 1. In freesurferformats, indices are converted to start at 1 when they are loaded, to be compatible with R. When the file is written to disk, they are converted back to be compatible with other software. This holds for vertex indices and face indices. If you notice something else, it is a bug, and will be changed as soon as I get to know about it.

Sorry for the confusion.

I will read the part about r6classes later and reply in a separate message, too tired atm.

**Comment by dipterix** [comment]
No worries, I've corrected them in my package. R6 classes are just a recommendation that might be helpful for backward compatibility support.

**Comment by dfsp-spirit** [comment]
In general, I am trying to **(1)** mark breaking changes in the release notes and **(2)** only break stuff after a grace period with proper deprecation warnings, so people know in advance that they will have to update their code. The latter does not hold for bugs, of course. That being said, the API of freesurferformats is still pretty young, and I guess sooner or later people using it will have to slightly adapt their code. I am well aware that this is annoying, and I am trying to keep the API as stable as reasonably possible.

Btw, I would like your opinion on the current behavior of freesurferformats with respect to the vertex indices. For most mesh file formats, it is not documented whether indices should start at 0 or 1, I guess it is up to the software writing the files. I am not sure which software can cope with which type of start indices, with the exception of FreeSurfer, which I know expects 0-based indices. 

- Would you prefer some metadata about the raw indices to be available after loading? (Whether they were incremented or not)?
- I guess there should be a flag when writing a mesh that forces that indices are written as they are, without modification?

**Comment by dipterix** [comment]
Thanks for clarification. That absolutely makes sense.

As far as I know, face index rarely starts from 1. In my package, I just set `face_idx <- face_idx - min(face_idx)` to make sure it always starts from 0. In `plotly`, an R package gaining growing number of users, it also uses 0 as starting index. Not very familiar with `rgl` system though, but I know `OpenGL` using C++ starts from 0. 

I guess because we eventually need to translate the code into other languages. These languages are usually very low-level. For example, `threeBrain` and `plotly` uses `WebGL`, which is internally C languages + GPU shaders (?). AFNI/SUMA uses C, naturally starting from 0. Face indices normally don't make too much sense in data analysis and you don't expect it to change once generated. Therefore people handling mesh files naturally follow the convention that face indices start from 0. However, you probably want to do more researches on the background, as these are my personal views. If your face index starts from 1, you might like to document this difference.

I personally would recommend to store "raw" data somewhere and expose derivatives. This might helps manage the code base in the future. OOP is not well supported in R, but `R6` should be enough. I'd happy to help.

**Comment by dfsp-spirit** [comment]
Thanks for your input and offer to help!

I'm busy with other stuff atm, but I'll think a bit more about it and do some research.

For most supported mesh file formats, I download example files from the internet and/or exported them from Blender or other software, then I looked at the vertex indices. I found a wild mix of zero-based and one-based files.
