### ISSUE TITLE
https to http

### ISSUE THREAD

**Issue by muschellij2** [dfsp-spirit/freesurferformats#22]
Failures for https://travis-ci.com/github/neuroconductor/freesurferformats/jobs/387818952 seem to indicate certificate is invalid (expired), so may want to change the `https` to `http`, you can see if you use Chrome and visit https://nifti.nimh.nih.gov/pub/dist/data/nifti2/avg152T1_LR_nifti2.nii.gz 

<img width="723" alt="Screen Shot 2020-09-21 at 12 37 59 PM" src="https://user-images.githubusercontent.com/1075118/93795407-53419900-fc07-11ea-8679-2237465b9a10.png">
<img width="879" alt="Screen Shot 2020-09-21 at 12 37 23 PM" src="https://user-images.githubusercontent.com/1075118/93795408-53da2f80-fc07-11ea-84e8-113063599b36.png">

**Comment by dfsp-spirit** [comment]
Yes, I have also noticed this. I fixed this on the develop branch earlier today in 0f2d9bfd. I created a mirror of the files on my own server and now download from there.

I released v0.1.13 on CRAN yesterday, and I have just committed cb15a111, which should lead to the release of the same version on neuroconductor.

**Comment by dfsp-spirit** [comment]
The commit was picked up and the new version v0.1.13 is on neuroconductor, so this seems to be resolved. Closing.
