### ISSUE TITLE
`read.fs.volume` silently returns NULL for files that do not satisfy any format checks

### ISSUE THREAD

**Issue by ToeKneeFan** [dfsp-spirit/freesurferformats#25]
I am not sure if this is intended behavior, but the `read.fs.volume` command appears to silently return a NULL value and do nothing if the `filepath` argument is a file that is not true for any of the [format conditionals](https://github.com/dfsp-spirit/freesurferformats/blob/cb2fc6a20a2f7303d4aba08d93fd13b7b5bd2190/R/read_fs_volume.R#L37-L43). For example,

```
freesurferformats::read.fs.volume("fakefile")
```
This is somewhat unanticipated behavior, as virtually any other file-reading command in R will trigger an error if a file does not exist or satisfy some basic expectations for that command. If this is intended behavior, it should probably at least be documented in the help file or give a warning if, for example, no matching file extension is detected for `format = "auto"`.

**Comment by dfsp-spirit** [comment]
That's a fair point, there should definitely be an error message instead of a silent NULL. I'm currently on mobile but I will verify it and fix it. Thanks for reporting it!

**Comment by ToeKneeFan** [comment]
> That's a fair point, there should definitely be an error message instead of a silent NULL. I'm currently on mobile but I will verify it and fix it. Thanks for reporting it!

Thank you for the excellent package and very prompt reply!

**Comment by dfsp-spirit** [comment]
I have verified and fixed the issue. The fix will be part of the next release. Thanks again for reporting.
