### ISSUE TITLE
[Feature Enhancement] Support asc, gii formats

### ISSUE THREAD

**Issue by dipterix** [dfsp-spirit/freesurferformats#9]
Hi, I'm writing a 3D viewer ([threeBrain](https://github.com/dipterix/threeBrain)) to visualize fs surface and volumes using R. Reading fs files is a headache for me until I came across your work. Thank you for developing this great package. I'm removing my old readers to depend on your fabulous `freesurferformats`.

Is there any plan to support reading asc or gii files just like reading from the default fs format?
For example, I only have `rh.pial.asc`, but I still want to use the same command to read from file as it were `rh.pial` via

```r
read.fs.surface('rh.pial')
```
Hopefully the function first check if `rh.pial` exists, if not, try `rh.pial.asc`, then `rh.pial.gii`. In such way the users don't have to care the format they are using. Here's an example:

```r
check_gifti <- function(){
  gifti_missing = system.file('', package = 'gifti') == ''
  if( gifti_missing ){
    stop('Package ', sQuote('gifti'), ' not installed. Please ...')
  }
}


read.fs.surface <- function(filepath, metadata = list()){
  
  if(!file.exists(filepath)){
    if(file.exists(file.path(filepath, '.asc'))){
      # read in ASCII file and return
      ...
    }else if(any(file.exists(file.path(filepath, c('.gii', '.gii.gz'))))){
      # check if gifti is installed
      check_gifti()
      
      # read in GIFTI file and return
      ...
    }
  }
  
  if (guess.filename.is.gzipped(filepath)) {
    fh = gzfile(filepath, "rb")
  }
  else {
    fh = file(filepath, "rb")
  }
  # always close the connection even if error occurs
  on.exit({ close(fh) }, add = TRUE)
  
  ...
  
}
```

**Comment by dfsp-spirit** [comment]
Hi dipterix,

glad to hear you like the package. I've had a look at your viewer a while ago, pretty cool.

1) Support for ASCII versions of the files is definitely on the list. I did not need it so far, but it's not much work. I will add it to the next release.

2) On the idea of also supporting gifti surfaces (or other volume/morphometry/whatever formats which are implemented in other packages): I thought about this. So far, I wasn't sure whether freesurferformats (fsf) )is the level on which this should be solved. E.g., I felt that the users of fsf should wrap `read.fs.surface` and some gifti function to create a more general function, like you described it. But maybe it's a good idea to supply it in fsf so there is a standard way. I will look into it and let you know.

Best,

Tim

**Comment by dipterix** [comment]
Thanks Tim, that sounds great :)

I did some experiment to use S3 generics (in my package, but I think it might be better in yours)

```r
# S3 generic
read_fs_curv <- function(path, ...){
  class(path) <- c('native', 'gifti', 'ascii', class(path))
  UseMethod('read_fs_curv', object = path)
}

# read.fs.surface
read_fs_curv.native <- function(path, ...){
  
  # try to read via read.fs.surface
  res <- tryCatch({
    freesurferformats::read.fs.surface(path, ...)
  }, error = function(e){
    NULL
  })
  
  # succeed
  if(!is.null(res)){
    return(res)
  }
  
  # failed, next method (gifti)
  NextMethod('read_fs_curv')
  
}

# Gifti can be implemented later by other packages
# implemetation of ASCII reader
read_fs_curv.ascii <- function(path, ...){
  res <- tryCatch({
    asc_path = paste0(path, '.asc')
    read.table(asc_path)[[5]]
  }, error = function(e){
    NULL
  })
  
  # succeed
  if(!is.null(res)){
    return(res)
  }
  
  # failed, next method (whatever implemented by other packages)
  NextMethod('read_fs_curv')
}

read_fs_curv.default <- function(...){
  stop('File is invalid')
}

read_fs_curv(path)
```

The benefit is that anyone who want to implement other kind of readers only need to implement `read_fs_curv.xxx`. 

Hope this helps.


Btw, one thing I realize when refactoring my code is you close the reader connection at the end of functions, like:
```r
read.fs.surface <- function(...){
  fh = file(filepath, "rb")

  ... (parse)

  close(fh)
}
```

This could cause problem when parsing process goes wrong. Personally I suggest
```
fh = file(filepath, "rb")
on.exit({ close(fh) }, add=TRUE)

... (parse)
```
to always close the connection.

**Comment by dfsp-spirit** [comment]
Some good ideas, thanks. 

Btw, I also looked into S3 generics recently. E.g., the latest fsf release assigns a class value to the return value of functions like `read.fs.surface` and `read.fs.annot`, and S3 methods for `print` and `is` are implemented. I will add plot methods in the `fsbrain` package soon.

**Comment by dfsp-spirit** [comment]
@dipterix You can try the new `read_nisurface` function in the dev version (just get the master branch via `install_github`) now. It should do what you want.

See the last unit test in the file [tests/testthat/test-read-nisurface.R](https://github.com/dfsp-spirit/freesurferformats/blob/master/tests/testthat/test-read-nisurface.R) for an example.

Reading FreeSurfer ASCII surface format and gifti is implemented already. (The `gifti` package is only suggested, not required.)

**Comment by dfsp-spirit** [comment]
This is in v0.1.8, which I just released. Closing.
